// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgUqZM2KLnMp9a26UZc2VB7PTHWS-59kc',
    appId: '1:626181265807:web:64e161bc10e495e05f93fa',
    messagingSenderId: '626181265807',
    projectId: 'learning-hub-e41f5',
    authDomain: 'learning-hub-e41f5.firebaseapp.com',
    storageBucket: 'learning-hub-e41f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm-n_fXE8Y5u4CFNo0YwdOgYzmAcy8tAo',
    appId: '1:626181265807:android:4333fc42ab15a0855f93fa',
    messagingSenderId: '626181265807',
    projectId: 'learning-hub-e41f5',
    storageBucket: 'learning-hub-e41f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUqufKG77mXCHR42NzAzpwLPXZ-50dRxo',
    appId: '1:626181265807:ios:95bf0f32eee9540a5f93fa',
    messagingSenderId: '626181265807',
    projectId: 'learning-hub-e41f5',
    storageBucket: 'learning-hub-e41f5.appspot.com',
    iosClientId: '626181265807-159eemq60os07b04vbm2van0gbrs3ctn.apps.googleusercontent.com',
    iosBundleId: 'com.example.learninghubapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUqufKG77mXCHR42NzAzpwLPXZ-50dRxo',
    appId: '1:626181265807:ios:95bf0f32eee9540a5f93fa',
    messagingSenderId: '626181265807',
    projectId: 'learning-hub-e41f5',
    storageBucket: 'learning-hub-e41f5.appspot.com',
    iosClientId: '626181265807-159eemq60os07b04vbm2van0gbrs3ctn.apps.googleusercontent.com',
    iosBundleId: 'com.example.learninghubapp',
  );
}
